### ISSUE TITLE
Confusing imports in `NumParser.py`

### ISSUE THREAD

**Issue by dennlinger** [vivkaz/CQE#1]
When installing the library, I'm encountering a mismatched naming convention of your library.

I'm a bit confused by the imports made in ll. 18-22 of `NumParser.py`.
It seems you refer internally to a (previous?) version named `numparser`, which throws a `ModuleNotFoundError` when I attempt to `from CQE import NumParser`.

Complete Traceback:
```
>>> from CQE import NumParser
/home/dennis/anaconda3/envs/cqe/lib/python3.9/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dennis/CQE/CQE/NumParser.py", line 18, in <module>
    from numparser import NumberNormalizer
ModuleNotFoundError: No module named 'numparser'
```

**Comment by dennlinger** [comment]
IMO, all of these lines should be relative package-level imports, e.g.,

```
from . import NumberNormalizer
from .rules import rules
# etc
```
